### PR TITLE
react component, fix .env inclusion unsder windows, close #17

### LINKED ISSUE #17: Add specialisation during command execution, like install@cordova

### PR DESCRIPTION
**Pull request by VladyslavKurmaz**

### CODE REVIEW

**Comment by VladyslavKurmaz** [comment]
retest this please

File: src/component.js [hunk 1]
```diff
@@ -608,7 +613,14 @@ class Component {
...
     for(const step of steps) {
-      const list2execute = this.findStep(step, filter, this.home, cntx.clone(), [], []);
+      let s = step;
+      let c = null;
+      const parts = step.split('@');
+      if (parts.length > 1) {
+        s = parts[0];
+        c = this.resolve([parts[1]]);
+      }
+      const list2execute = this.findStep(s, filter, this.home, cntx.clone(), [], [], c[0]);
```
Comment (VladyslavKurmaz) [inline src/component.js]: MAJOR TypeError can be thrown as "c" might be null or undefined here. [rule](http://159.65.230.204:9000/coding_rules#rule_key=javascript%3AS2259)

**Comment by VladyslavKurmaz** [comment]
SonarQube analysis reported 1 issue
* ![MAJOR][MAJOR] 1 major

Watch the comments in this conversation to review them.

[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
